### ISSUE TITLE
F-Droid cannot build recent versions

### ISSUE THREAD

**Issue by mvglasow** [signalwareltd/rtl_tcp_andro-#12]
The latest version on F-Droid is 2.2, dated December 2014. They disabled 3.01 (which seems to be the first one after the AS migration) as there seem to have been some gradle/JNI issues:

https://f-droid.org/wiki/page/marto.rtl_tcp_andro

Any chance you can sort this out? F-Droid is the main distribution channel for all those who don’t want to (or cannot) use Google Play. The maintainers are usually happy to receive contributions from app developers, and will gladly help you sort out any issues.

**Comment by martinmarinov** [comment]
Hello,

The page you have linked to does not specify what precise jni issues they are experiencing building the app.

Version 3.05 featured a change to update gradle configuration. This means it is possible the issues F-droid has been having might have gone away with that change.

Martin

**Comment by tomikmar** [comment]
I created new issue on F-Droid regarding this:
* https://gitlab.com/fdroid/fdroiddata/issues/871

**Comment by Bubu** [comment]
Version 3.06 added to f-droid. It should appear in the repository in the next days.
@martinmarinov Would you consider tagging the release versions in git? Then new versions could automatically be picked up by f-droid.

**Comment by tomikmar** [comment]
Version 3.06 is available on F-Droid:
* https://f-droid.org/packages/marto.rtl_tcp_andro/
