### ISSUE TITLE
False positive on VirusTotal (Webroot)

### ISSUE THREAD

**Issue by tomikmar** [signalwareltd/rtl_tcp_andro-#17]
VirusTotal reported false positive when I uploaded the latest release:
* https://github.com/martinmarinov/rtl_tcp_andro-/blob/master/app/app-release.apk
* https://www.virustotal.com/#/file/5deb6a43953df02953b5864cb729938c3f0121a91ea805e43eade05653982d49/detection

![false-positive](https://user-images.githubusercontent.com/5788375/30251077-5431d468-9659-11e7-8371-0e836701fec0.png)

**Comment by tomikmar** [comment]
I reported false positive to Webroot.

**Comment by martinmarinov** [comment]
Thanks
