### ISSUE TITLE
Error on  New Android devices because of new target api

### ISSUE THREAD

**Issue by ebc81** [signalwareltd/rtl_tcp_andro-#37]
onStart
RtlSdr: found 1 device opening options
HackRF: found 0 device opening options
Only 1 option available, no need to ask user. Opening rtl-sdr /dev/bus/usb/001/003
Closing service
Queueing
Arguments SdrTcpArguments{gain=24, samplerateHz=1024000, frequencyHz=91800000, address='0.0.0.0', port=14423, ppm=0}
Starting service with device rtl-sdr /dev/bus/usb/001/003
Caught exception IllegalArgumentException: marto.rtl_tcp_andro: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
 -> PendingIntent  -> UsbPermissionObtainer  -> RtlSdrDevice  -> RtlSdrDevice$1 
Closed service due to exception IllegalArgumentException: marto.rtl_tcp_andro: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
ERROR STARTING! Reason: unknown_error

**Comment by ebc81** [comment]
Error is here

  manager.requestPermission(usbDevice, PendingIntent.getBroadcast(ctx, 0, new Intent(ACTION_USB_PERMISSION), 0));

you should add explicit FLAG_MUTABLE 

https://developer.android.com/reference/android/app/PendingIntent#FLAG_MUTABLE

**Comment by martinmarinov** [comment]
Issue should be closed with latest update from yesterday. Please let me know if it has been fixed and thanks for reporting.

**Comment by ebc81** [comment]
is fixed
