### ISSUE TITLE
Add dump1090 to compatible apps

### ISSUE THREAD

**Issue by ebc81** [signalwareltd/rtl_tcp_andro-#40]
Hi,
Could you add Dump1090 Android to the list of compatible apps. Thnaks
https://play.google.com/store/apps/details?id=eu.ebctech.dump1090

**Comment by martinmarinov** [comment]
Added in https://github.com/signalwareltd/rtl_tcp_andro-/commit/be8f3fd076347b8262d0eb81e9deaab977d67395
