### ISSUE TITLE
NooElec

### ISSUE THREAD

**Issue by apertureless** [signalwareltd/rtl_tcp_andro-#42]
Did someone got it working with NooElec Donges?
I have tried the Nooelec NESDR Mini 2 and the Nooelec NESDR SMArt XTR but both would not get recognized.

**Comment by tomcat-xx** [comment]
Yes, just yesterday I got a NESDR SMArt v5 and it is working.

**Comment by apertureless** [comment]
Hm yeah seems to be a problem with NetHunter. Got it running on my other phone with stock rom.
