### ISSUE TITLE
NRSC5 / HD Radio Success

### ISSUE THREAD

**Issue by ferrellsl** [signalwareltd/rtl_tcp_andro-#43]
I've been able compile a native Android nrsc5 binary to decode HD Radio streams and play them with this driver via the Termux command line.

Alternatively, you can install a proot, Linux on Android distro and decode the audio from there with a very nice GUI such as this one:   
https://github.com/markjfine/nrsc5-dui

Instructions to do all of the above can be found here:  https://github.com/theori-io/nrsc5/issues/277

**Comment by signalwareltd** [comment]
Sounds great. If you ever publish an app in any appstore and would like me to add it to the README do let me know by re-opening the issue.
