### ISSUE TITLE
Add support for RTL-SDR Blog V4

### ISSUE THREAD

**Issue by rtlsdrblog** [signalwareltd/rtl_tcp_andro-#44]
Hi, just wanted to get in touch to see what the best way would be to add support for the RTL-SDR Blog V4? This is a new RTL-SDR dongle i'm releasing for sale, but unfortunately the hardware changes mean that it's not compatible with the current drivers. https://www.rtl-sdr.com/rtl-sdr-blog-v4-dongle-initial-release/ 

Basically there needs to be three main changes:

1) Set R828D dongles to use a 28.8 MHz LO instead of 16 MHz (can maintain compatibility with existing R828D dongles by checking an EEPROM string in V4 dongles)
2) Activate the appropriate R828D RF inputs based on frequency
3) Automatically upconvert the frequency when tuned to HF signals (as there is a built in upconverter)

These changes are implemented at https://github.com/rtlsdrblog/rtl-sdr-blog-minimal

Are you accepting PR's? If you like I can do a PR on your code with the necessary changes.

**Comment by signalwareltd** [comment]
Latest pull request has been merged and I've issued an update to new version of the app v3.15 that now has the changes. The new version should be live in Google Play within hours and in Amazon within days.

Do let me know if there's any issues with the new release.
